<?php

/**
 * A use case for handling when a ticket is reassigned
 */

// TODO: clean up this use case
class ReassignTicket {

	private $previousEmail;

	/**
	 * @param $form
	 * @param $entry_id
	 * @param $object
	 *
	 * @return void
	 */
	function reassign_ticket( $form, $entry_id, $object = null ) {
		// TODO: clean up this method
		BS_Log::info( "after_ticket_holder_updated TRIGGERED -------" );

		if ( get_permalink() == SITE_URL . '/view/invited-guests-details/' ) {
			$this->handle_ticket_reassignment( $entry_id, $this->previousEmail, $object, $form );
		}
		if ( get_permalink() == SITE_URL . '/view/dashboard/' ) {

			$dashboard = DashboardRepository::get_one_by_id( $entry_id );

			if ( $dashboard->certificateOfInsurance !== '' ) {
				$dashboard->hasCertificateOfInsuranceBeenUploaded = 'Yes';
				DashboardRepository::update( $dashboard );
			}
		}

		$this->previousEmail = null;

		BS_Log::info( "after_ticket_holder_updated COMPLETE -------" );
	}

	/**
	 * @param $entry_id
	 * @param $previousEmail
	 * @param $object
	 * @param $form
	 *
	 * @return void
	 */
	function handle_ticket_reassignment( $entry_id, $previousEmail, $object, $form ): void {
		$guestDetails = GuestDetailsRepository::get_one_by_id( $entry_id );
		$newEmail     = $guestDetails->email;
		BS_Log::info( "OLD EMAIL: $previousEmail" );
		BS_Log::info( "NEW EMAIL: $newEmail" );

		if ( ! empty( $this->previousEmail ) && $previousEmail !== $newEmail ) {
			//Remove previous ticket holder as user if not contact person
			$user   = get_user_by_email( $previousEmail );
			$userID = $user->ID;
			if ( intval( $userID ) !== intval( get_current_user_id() ) ) {
				wp_delete_user( $userID );
				BS_Log::info( "USER DELETED: $previousEmail" );
			} else {
				//Remove Ticket Holder membership from Contact Person
				$this->get_and_delete_transaction();
			}
			//Run all feeds for form
			$object = $object ?: new stdClass();
			add_filter( 'gform_is_feed_asynchronous', '__return_false', 1294873 );
			gf_apply_filters( array( 'gform_entry_post_save', $form['id'] ), $object->entry, $form );
			remove_filter( 'gform_is_feed_asynchronous', '__return_false', 1294873 );

			//Reset Contact Person as entry creator
			$guestDetails->createdBy = get_current_user_id();
			GuestDetailsRepository::update( $guestDetails );

			wp_redirect( SITE_URL . '/view/invited-guests-details/' );
			BS_Log::info( "after_ticket_holder_updated COMPLETE -------" );
			exit;
		}
	}

	function get_and_delete_transaction() {
		// TODO: move this into MemberPressAdapter
		$userTransaction = MeprTransaction::get_all_by_user_id( get_current_user_id() );
		BS_Log::info( "USER TRANSACTIONS" );
		BS_Log::info( $userTransaction );

		// Iterate through the array of objects
		foreach ( $userTransaction as $usrTxn ) {
			if ( $usrTxn->product_id == MembershipType::ATTENDEE ) {
				$txn = $usrTxn;

				break; // Break out of the loop since we found the desired product
			}
		}
		BS_Log::info( "TARGET TRANSACTION" );
		BS_Log::info( $txn );

		$curlUrl = SITE_URL . '/wp-json/mp/v1/transactions/' . $txn->id;
		BS_Log::info( "CURL URL: $curlUrl" );
		// Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
		$ch = curl_init();

		curl_setopt( $ch, CURLOPT_URL, $curlUrl );
		curl_setopt( $ch, CURLOPT_RETURNTRANSFER, 1 );
		curl_setopt( $ch, CURLOPT_CUSTOMREQUEST, 'DELETE' );

		$headers           = array();
		$memberPressApiKey = $this->get_memberpress_api_key();
		$headers[]         = 'Memberpress-Api-Key: ' . $memberPressApiKey;
		curl_setopt( $ch, CURLOPT_HTTPHEADER, $headers );

		$result = curl_exec( $ch );
		if ( curl_errno( $ch ) ) {
			echo 'Error:' . curl_error( $ch );
		}
		BS_Log::info( "TRANSACTION DELETION RESULT: " );
		BS_Log::info( $result );
		curl_close( $ch );
	}

	/**
	 * @return mixed|null
	 */
	function get_memberpress_api_key() {
		$entry = sbFormMethods::get_gform_entry( FormIds::FORM_ID_47_SECRETS, 'memberpress_api_key', 1 );

		return $entry['3'];
	}

	function set_current_ticket_holder_email( $form, $entry_id, $object = null ) {
		if ( get_permalink() == SITE_URL . '/view/invited-guests-details/' ) {
			$guestDetails        = GuestDetailsRepository::get_one_by_id( $entry_id );
			$this->previousEmail = $guestDetails->email;
			BS_Log::info( "PREVIOUS EMAIL IN BEFORE UPDATE: $this->previousEmail" );
		}
	}
}