<?php

class  FormIds {

	const FORM_ID_8_GUEST_DETAILS_REPEATER = 8;
	const FORM_ID_34_PORTAL_DASHBOARD = 34;
	const FORM_ID_5_BUY_TICKETS = 5;
	const FORM_ID_37_REGISTER_AS_AN_ATTENDEE = 37;
	const FORM_ID_23_MANAGE_GUESTS = 23;
	const FORM_ID_25_SIGN_EXHIBITOR_CONTRACT = 25;
	const FORM_ID_19_SIGN_THE_ATTENDEE_WAIVER = 19;
	const FORM_ID_26_REGISTER_AS_AN_EXHIBITOR = 26;
	const FORM_ID_33_QR_CODE_CHECKIN = 33;
	const FORM_ID_32_QR_CODE_LEAD_CAPTURE = 32;
	const FORM_ID_38_REGISTER_AS_A_SPEAKER = 38;
	const FORM_ID_43_INITITATE_EXHIBITOR_REGISTRATION = 43;
	const FORM_ID_47_SECRETS = 47;
}